variables:
  APP_NAME: clear-chain

stages:
  - build
  - push

build_job:
  image: docker:latest
  stage: build
  only:
    - master
  before_script:
    - echo "Start build project clear-chain"......"
  script:
    - docker build -t clear-chain:latest .

push_job:
  image: docker:latest
  stage: push
  only:
    - master
  before_script:
    - echo 'Start push image to docker hub......'
  script:
    - docker tag clear-chain:latest wylu1037/hust:clear-chain
    - docker push wylu1037/hust:clear-chain