variables:
  APP_NAME: clear-chain

stages:
  - build

build_job:
  image: docker:latest
  stage: build
  only:
    - master
  before_script:
    - echo "Start build project clear-chain......"
  services:
    - docker:dind
  script:
    - docker build -t clear-chain:latest .
    - echo 'Start push image to docker hub......'
    - docker tag clear-chain:latest wylu1037/hust:clear-chain
    - docker push wylu1037/hust:clear-chain
