variables:
  PROJECT_NAME: clear-chain
  IMAGE_NAME: clear-chain:latest

stages:
  - build

build_job:
  image: docker:latest
  stage: build
  only:
    - master
  before_script:
    - echo "Start build project \"$IMAGE_NAME\"......"
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - echo 'Start push image to docker hub......'
    - docker "$HUB_PASSWORD" | login --username $HUB_USERNAME --password-stdin
    - docker tag $IMAGE_NAME $HUB_USERNAME/hust:$PROJECT_NAME
    - docker push $HUB_USERNAME/hust:$PROJECT_NAME
